services:
  app:
    container_name: hls-api
    build:
     context: .
     dockerfile: Dockerfile
    restart: always
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
    volumes:
      - ./:/app
    depends_on:
      - postgres
    environment:
      - PORT=${PORT}
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - internal
  postgres:
    container_name: hls-postgres
    build:
     context: ./database
     dockerfile: Dockerfile
    restart: always
    volumes:
      - hls:/var/lib/postgres/data
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - internal

volumes:
  hls:
networks:
  internal:
    driver: bridge

